HelpInfo,C:\eda\Microsemi\Libero\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\eda\Microsemi\Libero\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:Kart_Board
Implementation;Compile;RootName:Kart_Board
Implementation;Compile||(null)||Please refer to the log file for details about 25 Warning(s)||Kart_Board_compile_log.rpt;liberoaction://open_report/file/Kart_Board_compile_log.rpt||(null);(null)
Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/98304003||Info: I/O Bank Assigner detected (2) out of (4) I/O Bank(s) with locked I/O technologies.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:Kart_Board
Implementation;Place and Route||(null)||Please refer to the log file for details about 2 Info(s)||Kart_Board_placeroute_log.rpt;liberoaction://open_report/file/Kart_Board_placeroute_log.rpt||(null);(null)
Implementation;Generate Bitstream;RootName:Kart_Board
